### ISSUE TITLE
Problems with user defined constants

### ISSUE THREAD

**Issue by onzalo** [mepx/mepx-binaries#1]
I installed mepx with the latest package "mepx64.deb" (2017.11.21.0-beta), xubuntu 16.04.

There are two problems when working with user defined constants:

1) By clicking on the radio button "User defined", the list of constants and the buttons "Add" and "Delete" remain disabled.
I have been able to deal with that bug by changing the constants probabilities again, after that the buttons are enabled.

2) When loading a saved project with user defined constants, the constants aren't loaded correctly and it's necessary to delete them in order to execute the project.

Is the GUI source code available to help solve this?

Thank you very much. Good job!

[mepx_project_2018_04_03_03_40_57.xml.zip](https://github.com/mepx/mepx-binaries/files/1870523/mepx_project_2018_04_03_03_40_57.xml.zip)

**Comment by mihaioltean** [comment]
thanks.
will fix the problem soon.

**Comment by mihaioltean** [comment]
I have fixed the bug and uploaded a new version: 2018.04.04.
Please confirm that it works on your side.

**Comment by onzalo** [comment]
Thanks for the quick fix. I just created a new project and the problem was solved.
