### ISSUE TITLE
Mod operator fails in vba generated code 

### ISSUE THREAD

**Issue by douglashurt** [mepx/mepx-binaries#2]
Problem:
After doing the training on a data set and selecting to develop the code results in vba. I have noticed that the vba mod function fails most of the time with a division by zero error even though nether value is zero. From my understanding the vba system treats any value less then 1 as a zero, as vba doesn't handle floating points, in the mod operation. So, 12.3 mod 0.0156 will produce and error.

Solution:
Change the vba generated code
 from
 prg[#]=prg[#] mod prg[#] 
To
Prg[#]=Evaluate("MOD(" & prg[#] & "," & prg[#] & ")")

**Comment by mihaioltean** [comment]
I have released version 2024.4.14 which includes a fix to this problem.

The new code (in libmep) for generating VBA is:

```cpp
case O_FMOD:
if (data_type == MEP_DATA_LONG_LONG)
	snprintf(tmp_s, 100, "prg(%u) Mod prg(%u)", adr1, adr2);
else // for double
	snprintf(tmp_s, 100, "Evaluate(\"MOD(\" & prg(%u) & \",\" & prg(%u) & \")\")", adr1, adr2);
```

Please check and confirm.
Thank you for helping!

**Comment by douglashurt** [comment]
Thank you for the new release. This has been verified, fixed, on my test dataset. I will exercise it a little more with different data to exercise the code a little better.

**Comment by douglashurt** [comment]
Resolved.
